// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ljqdenhtbcolnahayovk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxqcWRlbmh0YmNvbG5haGF5b3ZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0NzEyMDgsImV4cCI6MjA3NDA0NzIwOH0.r7k0RKX_icwheAeOoT7b73fodYOv4C2LdKA1jkx5LrQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});